.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitcoinreco_qt test_bitcoinreco_qt
clean: FORCE
	$(MAKE) -C .. bitcoinreco_qt_clean test_bitcoinreco_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitcoinreco_qt_check
bitcoinreco-qt bitcoinreco-qt.exe: FORCE
	 $(MAKE) -C .. bitcoinreco_qt
